### ISSUE TITLE
Problem running inside docker-compose using volumes

### ISSUE THREAD

**Issue by furenku** [sharvit/mongoose-data-seed#27]
Hello!

This is probably a bit too specific, but I wanted to ask here anyways. Perhaps other people have run into the same situation? 

I am getting the following error when trying to run **md-seed run** inside a docker container. I am passing source code and mongoose models into the container via volumes

```
TypeError: this.connect is not a function
seed-docker |     at MdSeedRunner._callee2$ (/usr/local/lib/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:171:29)
```

Error screenshot:

![Screenshot from 2019-07-24 12-00-44](https://user-images.githubusercontent.com/1314371/61813683-f2081500-ae0b-11e9-92c7-cd4153f89f17.png)

Here is my Dockerfile:
```Docker
FROM node:11


ENV HOME=/home/seeduser/seed

COPY . $HOME

WORKDIR $HOME

RUN npm install -g mongoose-data-seed@1


CMD md-seed run --dropdb
```

Finally, docker-compose.yml:

```yml
version: "3"
services:
  seed:
    container_name: seed-docker
    # build: ./seed-docker    
    build:    
      context: .
      dockerfile: ./seed-docker/Dockerfile
    volumes:
      - /path/to/seed:/home/seeduser/seed/
      - /path/to/models:/home/seeduser/seed/models
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    restart: always
    logging:
      driver: none
volumes:
  data-volume:


```
